// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Job struct {
	ID           string          `json:"id"`
	Text         string          `json:"text"`
	Description  string          `json:"description"`
	IsArchived   bool            `json:"isArchived"`
	IsDeleted    bool            `json:"isDeleted"`
	Tags         *string         `json:"tags"`
	Skills       *string         `json:"skills"`
	DeadlineDate *string         `json:"deadlineDate"`
	Attributes   *JobAttributes  `json:"attributes"`
	Requirement  *JobRequirement `json:"requirement"`
	User         *User           `json:"user"`
}

type JobAttributes struct {
	IsPermanent      *bool   `json:"isPermanent"`
	IsContract       *bool   `json:"isContract"`
	ContractDuration *string `json:"contractDuration"`
	Salary           *string `json:"salary"`
}

type JobAttributesInput struct {
	IsPermanent      *bool   `json:"isPermanent"`
	IsContract       *bool   `json:"isContract"`
	ContractDuration *string `json:"contractDuration"`
	Salary           *string `json:"salary"`
}

type JobRequirement struct {
	Experience *string `json:"experience"`
	Domain     *string `json:"domain"`
	Education  *string `json:"education"`
	Gender     *string `json:"gender"`
}

type JobRequirementInput struct {
	Experience *string `json:"experience"`
	Domain     *string `json:"domain"`
	Education  *string `json:"education"`
	Gender     *string `json:"gender"`
}

type NewJob struct {
	Text         string               `json:"text"`
	Description  string               `json:"description"`
	Tags         *string              `json:"tags"`
	Skills       *string              `json:"skills"`
	DeadlineDate *string              `json:"deadlineDate"`
	Attributes   *JobAttributesInput  `json:"attributes"`
	Requirement  *JobRequirementInput `json:"requirement"`
	UserID       *string              `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
